const HABIT_ITERATION_DAILY = 'DAILY'
const HABIT_ITERATION_WEEKLY = 'WEEKLY'
const HABIT_ITERATION_BIWEEKLY = 'BIWEEKLY'
const HABIT_ITERATION_MONTHLY = 'MONTHLY'

const HABIT_ITERATION_TYPES = [
  HABIT_ITERATION_DAILY,
  HABIT_ITERATION_WEEKLY,
  HABIT_ITERATION_BIWEEKLY,
  HABIT_ITERATION_MONTHLY
]
