export const HABIT_ITERATION_DAILY = 'DAILY'
export const HABIT_ITERATION_WEEKLY = 'WEEKLY'
export const HABIT_ITERATION_BIWEEKLY = 'BIWEEKLY'
export const HABIT_ITERATION_MONTHLY = 'MONTHLY'

export const HABIT_ITERATION_TYPES = [
  HABIT_ITERATION_DAILY,
  HABIT_ITERATION_WEEKLY,
  HABIT_ITERATION_BIWEEKLY,
  HABIT_ITERATION_MONTHLY
]
